- name: nats
  connector_type: nats
  config:
    connection_timeout: 30
    consumer_group: CDC
    consumer_name: consumer01
    max_reconnect_attempts: 10
    ping_interval: 120
    reconnect_wait: 2
    servers:
    - nats://localhost:4222
    subject: debezium.>
    tls_enabled: false
    use_jetstream: true
  description: ''
  tags: []
  created_at: 2026-02-02T12:23:20.949611900Z
  updated_at: 2026-02-02T12:23:20.949612Z
